version: '3'
volumes:
  pyszczek_db:
    external: true

services:
  db:
    image: postgres:12.0
    volumes:
      - pyszczek_db:/var/lib/postgresql/data
    env_file:
      - app.env
    ports:
      - "5432:5432"
    restart: always
